### ISSUE TITLE
Add supporting of masks.

### ISSUE THREAD

**Issue by eGavr** [bem/html-differ#119]
`html-differ` must support masks. This feature dramatically increases the comparison abilities.
For example,

```html
<tag attr="12345">
```

```html
<tag attr="{{\d+}}">
```

These two HTMLs should be considered to be equal.

Syntax of placeholders in `html-differ`  -> ```{{RegExp}}```, where

1.`{{` - opening identifier of the placeholder

2.`RegExp` - a regular expression for matching with the corresponding value in another HTML
  * has just the same syntax as a real JS RegExp written in a short form, i.e ```/String/```
  * can not contain whitespaces AS IS (in order to avoid conflicts with option `ignoreWhitespaces` and ```tokenizer``` of the tool), i.e -> ```{{  \d+}}``` is an invalid variant, BUT ```{{\s\d+}}``` is a valid one.
  * can not be written as an attribute of a tag (```htmlparser``` will not be able to detect which attributes are REAL and which of them are placeholders), i.e. -> ```<tag {{\d+}}>``` is an invalid variant, BUT ```<tag attr="{{\d+}}">``` is a valid one.

3.`}}` - closing identifier of the placeholder

**Comment by arikon** [comment]
My opinion:

```
{# \d+ #}
```

**Comment by eGavr** [comment]
Decided to use -> `{{RegExp}}`
