### ISSUE TITLE
Can we add tick, sharp, and some other chars to delimiters for differ?

### ISSUE THREAD

**Issue by zxqfox** [bem/html-differ#122]
![image](https://cloud.githubusercontent.com/assets/677518/6279875/a7a880ac-b8b6-11e4-8a7b-6433a82822ee.png)

**Comment by eGavr** [comment]
Yes, we can. So you can you say exactly which chars should be added as delimiters?

According the name of the issue, I've understood that you wanner such symbols as `#` and ```

Anything else?

**Comment by eGavr** [comment]
ping?

**Comment by zxqfox** [comment]
Ouch. I'm not sure which characters should be qualified as delimiters. Just want to note that characters used in `md` (`[]()#-*` and tick) should be added to that list imho ;-)

**Comment by eGavr** [comment]
I think I should add this ones:

* `\``
* `#`

**Comment by zxqfox** [comment]
Good 2 me!

**Comment by eGavr** [comment]
`-`and `*` are not a real word delimiters, I think. And such delimiters as `[]()` have already been added.
