### ISSUE TITLE
Use `chalk` instead of `colors`

### ISSUE THREAD

**Issue by andrewblond** [bem/html-differ#123]

**Comment by eGavr** [comment]
Аргументируй ;)

**Comment by andrewblond** [comment]
`chalk ` was created because the colors module does some really horrible things.

`colors` is currently the most popular string styling module, but it has serious deficiencies like extending `String.prototype` which causes all kinds of problems.

h̞̭̀e̵̦̠̪̘̗'̨l͎͖͇̩̻̮̟͞l̷͕̤̗̪̯ͅ ̨͇̥͚̗c̵̥͕̙͔͚͖͎ó̥m͘e̟͚͓̝̖͇͔͞ ̝f̢̗̝̖̫̦͕͇o̞̱̙r̗͎͓̻ ̛̝͉̺̮̦͔͔ý͍͓̺̣ó͙̠̤̝̩u̖̮̫͟!̤̹̟̬͞

**Comment by zxqfox** [comment]
:+1:
