### ISSUE TITLE
Escaping Quotes

### ISSUE THREAD

**Issue by blond** [bem/html-differ#133]
Escaping quotes should not be equal normal quotes.

**Example**

These HTMLs should not be equal:

```html
<div class="button__text">&lt;script&gt;alert("")&lt;/script&gt;</div>

```

```html
<div class="button__text">&lt;script&gt;alert(&quot;&quot;)&lt;/script&gt;</div>
```

**Comment by eGavr** [comment]
`html-differ` does not see the difference, because it seems that the above two HTMLs are really equal :)
