### ISSUE TITLE
вложенные html-элементы не попадают под маску

### ISSUE THREAD

**Issue by kompolom** [bem/html-differ#134]
[вот пример того что хочется получить](https://gist.github.com/kompolom/19e70ff1c336463a1a71) но никак не могу написать паттерн который бы подошел, хотя проверяю https://regex101.com/#javascript регулярка срабаывает

**Comment by eGavr** [comment]
Ни одна из ссылок не дает требуемой информации :)

На первую меня не пускает, а на второй не показывается регулярка.
Дай права, чтобы я мог перейти на первую ссылку и сюда можешь написать регулярку (я верю, что она корректна)

**Comment by kompolom** [comment]
https://gist.github.com/kompolom/19e70ff1c336463a1a71  еще раз ссылка на гист 
маска 

````
{{.*}}
{{(.|\n)*}}
````
ни одна не матчится на произвольный html. Для примера:

````html
<textarea class="textarea textarea_theme_vr textarea_size_l textarea_width_available textarea__control i-bem" id="uniq14455148478992" name="body" placeholder="Ваш комментарий" data-bem="{&quot;textarea&quot;:{}}"></textarea>
````

````html
<textarea {{(.|\n)*}}></textarea>
````

**Comment by kompolom** [comment]
Может просто совпадение, но заметил что регулярка стабильно не срабатывает на тексте где есть `=` в дифе она тогда отображается не как регулярка, а как ожидаемый текст (зеленая)

**Comment by eGavr** [comment]
А конкретно с каким HTML ты сравниваешь?

**Comment by kompolom** [comment]
выше пример с textarea

**Comment by eGavr** [comment]
Не,  я понял какая регулярка у тебя не работает. 

Я хочу увидеть два реальных HTML, которые html-differ должен посчитать одинаковыми :)

**Comment by kompolom** [comment]
@eGavr  как их показать?

**Comment by kompolom** [comment]
![screen28](https://cloud.githubusercontent.com/assets/6213808/10677571/ee407e00-7915-11e5-8625-2073cd4c9e1b.png)
Вот скрином сделал

**Comment by kompolom** [comment]
Посмотрел в отладчике, насколько я понял, маска применяется только к одному токену. 
https://github.com/bem/html-differ/blob/master/lib/utils/mask.js#L42 который в свою очередь заканчивается кавычками. Я правильно понял?

**Comment by eGavr** [comment]
Да, ты все верно понял, собственно я и хотел предложить тебе следующее:

```html
<textarea class="{{.*}}" id="{{.*}}" name="{{.*}}" placeholder="{{.*}}" data-bem="{{.*}}"></textarea>
```

**Comment by eGavr** [comment]
> @eGavr как их показать?

У `enb-bem-tmpl-specs` я так понял ты эту утилиту используешь, есть переменная среды окружения и опция, которая позволяет сохранять созданный в тесте HTML –> https://github.com/enb-bem/enb-bem-tmpl-specs#Опции

**Comment by kompolom** [comment]
@eGavr спасибо за ответ. Тогда хочу попросить добавить фичу, которая будет работать на произвольном количестве токенов. Если это возможно

**Comment by eGavr** [comment]
Очень странно хотеть на столько "не жестко" сравнивать HTML.

Вариант использования такой маски как ты хочешь фактически делает HTML не валидным, поэтому HTML-парсер в диффалке будет отрабатывать неправильно, поэтому и сравнение будет неправильным.

**Comment by kompolom** [comment]
@eGavr Вообще ты прав. Спасибо что помог разобраться. Последний вопрос. Как добавить маску на необязательный атрибут. Например, в html может быть `required=""` может `required`  а может и вообще не быть. Я как понимаю атрибут и его значение будут в разных токенах. Как сделать чтобы все три html посчитались одинаковыми? Или это тоже не стоит хотеть?

**Comment by eGavr** [comment]
Я бы сказал, что тоже не стоит хотеть делать, что у тебя там за тесты ? :)

Ты уверен, что такое хотеть нормально ? :) (с точки зрения сравнения одинаковой работоспособности HTML)

Есть у диффалки [фича](https://github.com/bem/html-differ#ignoreattributes-array), которая игнорирует значение атрибута, но она обязательно требует наличие атрибута.

**Comment by kompolom** [comment]
Спасибо за разъяснения!
