### ISSUE TITLE
Feat request: Should ignore duplicates in class names list

### ISSUE THREAD

**Issue by zxqfox** [bem/html-differ#138]
`<div class="popup welcome popup popup welcome"></div>`
should be equivalent to
`<div class="welcome popup"></div>`

**Comment by eGavr** [comment]
Are you sure that it is necessary to do do ?

**Comment by zxqfox** [comment]
ex1:
```
var elem = document.createElement('div');
elem.className = 'popup popup open popup';
console.log(elem.classList); // ["popup", "popup", "open", "popup"]
```

ex2:
```js
var 

var elem = document.createElement('div');
elem.classList.add('popup')
elem.classList.add('popup')
elem.classList.add('open')
elem.classList.add('popup')
console.log(elem.classList); // ["popup", "open"]
```

https://www.w3.org/TR/html401/struct/global.html#h-7.5.2

**Comment by eGavr** [comment]
It should be an option or used by default?

**Comment by zxqfox** [comment]
I don't see why it should be hidden under option. It's like resorting class names inside class attribute.
