### ISSUE TITLE
Insecure dependencies

### ISSUE THREAD

**Issue by UziTech** [bem/html-differ#155]
Are there any plans to update the [insecure dependencies](https://david-dm.org/bem/html-differ) or is this repo unmaintained?

/cc @alexbaumgertner, @arikon, @awinogradov, @belozer, @blond, @dfilatov, @dosyara, @eGavr, @gela, @incrop, @indutny, @levonet, @mishaberezin, @mishanga, @narqo, @SevInf, @tadatuta, @tavriaforever, @tormozz48, @varya, @veged, @vithar, @voischev, @yarastqt, @Yeti, @zxqfox

**Comment by alexbaumgertner** [comment]
At least lodash will update in https://github.com/bem/html-differ/pull/147.

Unfortunately I'm not a maintainer.
@eGavr could you help?

**Comment by arsonry** [comment]
I'm assuming nothing ever came of this?  html-differ has a few failed audits thanks to out of date/insecure dependencies still.

**Comment by UziTech** [comment]
I don't believe this repo is maintained anymore. We ended up forking it and updating it ourselves.

**Comment by arsonry** [comment]
Kinda figured this was the case.  Noticed there's been a PR to update the lodash vulnerability for...almost 2 years now.  We'll have to do the same as you then!  Thanks!

**Comment by tadatuta** [comment]
Just merged https://github.com/bem/html-differ/pull/147 and  https://github.com/bem/html-differ/pull/158/

**Comment by tadatuta** [comment]
html-differ@1.4.0 released

**Comment by badamo37** [comment]
Awesome, thank you!!
